- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- stylesheets/SimpliGov-basic.css
Adding these files to the remote repository
> Fix: Add README, License, Code of Conduct

- data_sources/Production Department Permissions Data Source copy.csv
- data_sources/Youth Pass Municipality Contacts and Zip Codes.csv
- stylesheets/SimpliGov-basic.css
We removed two zip codes from our eligibility list, and this PR updates the CSV documents accordingly. Asana ticket: https://app.asana.com/0/1170867711449497/1200850416294339/f 
This PR also adds a distinct Production data source to better maintain the environment and prepare us for the rollout of actual user data. This data source contains test users for penetration testing, ensuring that they will have all appropriate permissions as needed for their individual departments.
> Fix: Remove zip codes and Add production data source

- stylesheets/SimpliGov-basic.css
Accessibility review by WGBH turned up potential improvements we can make to the Youth Pass form. This PR implements these improvements with:
- Updated styling for primary/secondary buttons to match MBTA style guide
- Updated styling for standard and RegEx error messages to match MBTA style guide
- Updated styling for link elements
Asana ticket: https://app.asana.com/0/1170867711449497/1200880153168107/f
> Feat: Accessibility Color Changes

- cypress/automated-tests/youth-pass/eligibilty-checker-blockers.spec.js
This PR adds a Cypress script to test that the Youth Pass eligibility checker blocking conditions are working as expected. Applicants with ineligible zip codes, or ages, school or partner program enrollment status should not be able to progress and complete their applications. 
Asana ticket: https://app.asana.com/0/1170867711449497/1200759639068377/f
> Feat: Add eligibility checker automated test

- package-lock.json
This PR updates dependencies per Cypress command line feedback. 
> Fix: Update cypress dependencies

- cypress/automated-tests/youth-pass/document-viewer-s3-urls.spec.js
- cypress/common/submit-application.js
This PR adds an automation script testing that we can see Document Viewer S3 URLs when a Youth Pass application is approved. This script confirms that our external API SimpliGov configuration is working properly. 
This PR also makes minor updates caused by the new Language translation epic. Several element selectors are affected by the new application tab order and the updated radio option values.
Asana ticket: https://app.asana.com/0/1170867711449497/1201488960297595/f
> Feat: Add document viewer url test

- cypress/automated-tests/youth-pass/address-section-required-fields.spec.js
- cypress/automated-tests/youth-pass/eligibility-checker-blockers.spec.js
- cypress/automated-tests/youth-pass/file-type-upload.spec.js
- cypress/automated-tests/youth-pass/personal-contact-sections-required-fields.spec.js
- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
Reverts mbta/reduced_fares#56, as we did not ultimately deploy to Production yesterday.
> Revert "Fix: Update automation scripts for Jan release"

- cypress/automated-tests/youth-pass/address-section-required-fields.spec.js
- cypress/automated-tests/youth-pass/document-viewer-s3-urls.spec.js
- cypress/automated-tests/youth-pass/eligibility-checker-blockers.spec.js
- cypress/automated-tests/youth-pass/file-type-upload.spec.js
- cypress/automated-tests/youth-pass/personal-contact-sections-required-fields.spec.js
- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
This PR will restore the changes made in [PR#56](https://github.com/mbta/reduced_fares/pull/56). These changes cannot go live until the SimpliGov Winter Release takes place and we have a successful deployment to Production.
> Revert "Revert "Fix: Update automation scripts for Jan release""

- README.md
No Asana ticket, just setting up a new computer and saw the need.
> docs: Add development setup instructions to the Readme

- package-lock.json
- package.json
No Asana ticket, Cypress just told me there was an upgrade available.
[Passing test suite](https://github.com/mbta/reduced_fares/runs/4973820544?check_suite_focus=true)
> build: Upgrade Cypress to the latest version 9.3.1

- stylesheets/Senior-Basic.css
Initial senior css for user testing. Will refine based on feedback. [Asana ticket](https://app.asana.com/0/1170867711449497/1201639031477255/f).
> Initial senior css for user testing

- cypress.json
- cypress/automated-tests/senior/successful-senior-submission.spec.js
- cypress/common/birthdate-constants.js
Asana ticket: [Senior Automated Test: Success Path](https://app.asana.com/0/1200240595613188/1201687530646478)
Include a submission:
• with an email address
• without an email address
Include this test in GitHub Actions runs against preprod, but not
against prod.
[Successful test run](https://github.com/mbta/reduced_fares/runs/4974326904?check_suite_focus=true)
> test: Add a Cypress test for the Senior success path

- .github/workflows/automation-prod.yml
- cypress/automated-tests/senior/birth-date-validation.spec.js
- cypress/automated-tests/senior/successful-senior-submission.spec.js
- cypress/common/birthdate-constants.js
Asana ticket: [Senior Automated Test: Birthday Error Path](https://app.asana.com/0/1200240595613188/1201687530646480)
Add to GitHub prod testing workflow.
> test: Test error if the applicant is under 65

- .github/workflows/automation-prod.yml
- cypress/automated-tests/senior/required-fields.spec.js
- cypress/automated-tests/senior/successful-senior-submission.spec.js
Asana ticket: [Senior Automated Test: Required Fields](https://app.asana.com/0/1200240595613188/1201695457692870)
Add to the GitHub prod testing workflow.
> test: Add a Cypress test for all required fields

- .github/workflows/automation-prod.yml
The application is not yet deployed to production so these are failing.
> fix: Stop running senior tests in prod for now

- cypress/automated-tests/senior/required-fields.spec.js
- cypress/automated-tests/senior/successful-senior-submission.spec.js
No ticket, I just came across this while doing development.
Changes to the form seem to have altered this value.
> fix: Fix the selector for the final submit button

- package-lock.json
- package.json
> build: Update Cypress to the latest version 9.5.0

- stylesheets/Senior-Basic.css
Added accessible colors to upload pages. Asana ticket: [Implement Accessible Colors for File Upload - Senior](https://app.asana.com/0/1170867711449497/1201701654970846/f)
> Updating upload page colors for accessibility

- stylesheets/Senior-Basic.css
Asana ticket: [Add Example Photo to Instructions Page](https://app.asana.com/0/1170867711449497/1201708568852777/f)
Picture styling for accepted photo graphic. Width reduces at larger screen sizes. Border added.
> Add: picture styling including border

- stylesheets/Senior-Basic.css
Asana ticket: [Improve Focus on X to remove files - Senior](https://app.asana.com/0/1170867711449497/1201701654970843/f)
Used zeroheight styling on the x button to meet accessibility guidelines. Includes hover and focus effects. Updated the selectors for the dark grey text in the upload section.
> Senior styling x button

- stylesheets/Senior-Basic.css
Asana ticket: [Modal dialog error - update "Ok" button - Senior]( https://app.asana.com/0/1170867711449497/1201701654970849/f)
Updated modal buttons to meet color contrast and focus guidelines. Cleaned up button section.
> Accessible modal button colors

- stylesheets/Youth-Pass-Basic.css
Asana ticket: [Investigate Cause of CSS File Upload Failure for YP](https://app.asana.com/0/1113179098808463/1201764588138170/f)
This is a fix to allow the CSS file to be attached in SimpliGov. Removes .h3 border code.
> Fix: remove .h3 border

- cypress/automated-tests/senior/birth-date-validation.spec.js
- cypress/automated-tests/senior/required-fields.spec.js
- cypress/automated-tests/senior/successful-senior-submission.spec.js
This is a temporary state that I expect to roll back before long.
Related to the changes made for: [Hide Language Selection](https://app.asana.com/0/1200240595613188/1201957412884505)
> test: Fix the tests to compensate for hiding the language selection

- data_sources/Production Youth Permissions.csv
Asana ticket: [New Youth Pass admin: Framingham](https://app.asana.com/0/1170867711449497/1202019791864669/f)
Add `dionne_robinson@waysideyouth.org` to Production data source.
> add: new Framingham admin to prod data source

- stylesheets/Senior-Basic.css
- stylesheets/Youth-Pass-Basic.css
Precursor to: [Set up CSS linting in reduced_fares project](https://app.asana.com/0/1200240595613188/1201752498907673)
This PR only includes refactoring, no functional changes.
This enables the forthcoming stylelint check to pass: https://github.com/mbta/reduced_fares/actions/runs/2061087447
> refactor: CSS cleanup to prepare for stylelint rules

- data_sources/Production Senior Permissions.csv
- data_sources/Training Senior Permissions.csv
Asana ticket: [New CharlieCard Store Admin for Senior needs Access to SimpliGov](https://app.asana.com/0/1113179098808463/1202057944069874/f)
Add `tdegrace@MBTA.com` to senior training and production data sets.
> Add tdegrace@mbta.com to senior training and production data sources

- assets/senior_html/emails/application-submitted-in-store-pickup-english.html
- assets/senior_html/emails/application-submitted-mail-english.html
- assets/senior_html/emails/approved-by-mail-english.html
- assets/senior_html/emails/approved-in-store-english.html
- assets/senior_html/emails/denied-after-30-days-english.html
- assets/senior_html/emails/denied-english.html
- assets/senior_html/emails/request-more-info-english.html
- assets/senior_html/emails/resubmission-received-in-store-pickup-english.html
- assets/senior_html/emails/resubmission-received-mail-english.html
Asana ticket: [Add HTML to Senior email notifications](https://app.asana.com/0/1170867711449497/1201718185160791/f)
Wording and style are verified. Please check HTML and provide suggestions for linting tools if needed. The current formatting is meant to make entering translations easier, though I recognize it isn't standard.
> add: all Senior English email templates

- data_sources/Production Senior Permissions.csv
- data_sources/Training Senior Permissions.csv
Adding two new Admin to the Senior application permissions for Training and Production environments. 
Asana ticket: https://app.asana.com/0/1113179098808463/1202089256090185/f
> Feat: Add two new senior admin to training and prod

- data_sources/Production Youth Permissions.csv
Medford has requested a new Admin. This PR adds the new Admin to the Production data source. 
Asana task: https://app.asana.com/0/1170867711449497/1202190904729274/f
> Fix: Add new admin to Medford data source

- cypress.json
- cypress/automated-tests/blind/successful-blind-submission.spec.js
Asana ticket: [Blind Automated Test: Success Path](https://app.asana.com/0/1200240595613188/1202044779867077)
Test new and renewal applications, with and without an email address.
[Successful test run (of these tests)](https://github.com/mbta/reduced_fares/runs/6279033609?check_suite_focus=true)
> test: Cypress tests for the Blind form success path

- cypress/automated-tests/blind/required-fields.spec.js
Asana ticket: [Blind Automated Path: Required Fields](https://app.asana.com/0/1200240595613188/1202044779867084)
[Successful test run (of these tests)](https://github.com/mbta/reduced_fares/runs/6279527868?check_suite_focus=true)
> test: Cypress tests for the Blind form required fields

- data_sources/Production Senior Permissions.csv
- data_sources/Training Senior Permissions.csv
We got a request for a new CCS admin. This PR adds the new admin user to the Training and Prod data sources. 
Asana task: https://app.asana.com/0/1113179098808463/1202255593088887/f
> Fix: Add new CCS admin

- cypress/automated-tests/blind/required-fields.spec.js
- cypress/automated-tests/blind/successful-blind-submission.spec.js
Asana ticket: [Fix Automated Tests for Blind Access](https://app.asana.com/0/1170867711449497/1202405784075212/f)
• Skip the hidden language section
• Handle MCB ID vs blindness certification branch
[Successful CI run](https://github.com/mbta/reduced_fares/runs/6778757511?check_suite_focus=true)
> fix (test): Adjust the tests to match the current form behavior

- data_sources/Production Senior Permissions.csv
- data_sources/Training Senior Permissions.csv
This PR adds Mary Redman as a new Admin able to access the Senior, Blind, and TAP submissions. The PR also adds ten new admin slots (for a total of 25) to Training and Production, now that we have filled the 15 available admin slots for Training.
Asana task: https://app.asana.com/0/1113179098808463/1202438588644288/f
> Feat: Add QA admin and ten new admin slots

- cypress/automated-tests/youth-pass/successful-youth-pass-submission.cy.js
This is to merge a test fix into the `remove-emily-from-municipality-data` branch. @krisrjohnson21 please confirm, but I think with this change it relieves the concerns with https://github.com/mbta/reduced_fares/pull/163.
> test: Update test to match new email address

- data_sources/PreProd Senior Permissions.csv
Asana ticket: [Add additional admin "slots" to Senior and BA](https://app.asana.com/0/1113179098808463/1202444436331557/f)
Increase number of admin to 25 in PreProd data source so permissions can be set in SimpliGov.
> add admin slots in preprod

- cypress/automated-tests/blind/required-fields.cy.js
- cypress/automated-tests/blind/successful-blind-submission.cy.js
Asana ticket: [Fix Blind Access Automated Tests](https://app.asana.com/0/1200240595613188/1202480672295097)
[Successful test run](https://github.com/mbta/reduced_fares/runs/7505434900?check_suite_focus=true)
> test: Restore the language selection step to the Blind tests

- data_sources/Production Youth Permissions.csv
Now that Javier has left the Youth Pass program for Somerville, this PR removes his email from the Youth Pass permissions data source. 
Asana task: https://app.asana.com/0/0/1202722098361660/f
> Chore: Remove Javier from Somerville YP data source

- cypress/automated-tests/blind/required-fields.cy.js
- cypress/automated-tests/blind/successful-blind-submission.cy.js
Asana ticket: [Automated Testing for BA One-Page Form](https://app.asana.com/0/1200240595613188/1202670974816440)
The blind access form was converted from a wizard flow to a single-page
form. This adjusts the Cypress tests to match.
> fix(test): Blind support one-page form

- cypress.config.js
- cypress/automated-tests/tap/required-fields.cy.js
- cypress/automated-tests/tap/successful-tap-submission.cy.js
Asana tickets:
- [TAP Automated Test: Success Path](https://app.asana.com/0/1200240595613188/1202429475090102)
- [TAP Automated Path: Required Fields](https://app.asana.com/0/1200240595613188/1202429475090110)
• Successful form submissions with and without an email address
• Required fields
[Successful CI run](https://github.com/mbta/reduced_fares/runs/8100452175?check_suite_focus=true)
> test: Automated Cypress tests for the TAP form

- data_sources/Production Youth Permissions.csv
This PR adds a new Admin to the production Youth Pass data source for all Newton zip codes. 
Asana task: https://app.asana.com/0/1113179098808463/1202983077786278/f
> Chore: Add Newton YP Prod Admin

- .tool-versions
[Passing CI run](https://github.com/mbta/reduced_fares/actions/runs/3266150241/jobs/5369464259)
> deps: Update Node to the latest LTS version 16.18.0

- package-lock.json
- package.json
Consolidated and fixed versions of https://github.com/mbta/reduced_fares/pull/241 and https://github.com/mbta/reduced_fares/pull/238.
[Passing lint](https://github.com/mbta/reduced_fares/actions/runs/3266423342/jobs/5370139346)
[Passing CI](https://github.com/mbta/reduced_fares/actions/runs/3266438958/jobs/5370173073)
> deps: Consolidated stylelint updates

- cypress/automated-tests/youth-pass/parental-consent.cy.js
- cypress/common/birthdate-constants.js
Asana ticket: [Fix YP Automated Tests](https://app.asana.com/0/1170867711449497/1203523136593593/f)
This applies to any applicant under 13.
[Successful run in CI](https://github.com/mbta/reduced_fares/actions/runs/3752843381/jobs/6375463899)
> test: Cypress tests for Youth Pass parental consent

- cypress/automated-tests/tap/parental-consent.cy.js
- cypress/automated-tests/youth-pass/parental-consent.cy.js
Asana ticket: [Fix TAP Automated Tests](https://app.asana.com/0/1170867711449497/1203579691569788/f)
~~Depends on https://github.com/mbta/reduced_fares/pull/276~~
> test: Add a test for the new TAP parental consent flow

- cypress/automated-tests/blind/parental-consent.cy.js
Asana ticket: [Fix Blind Automated Tests](https://app.asana.com/0/696643827122369/1203579691569782/f)
~~Depends on https://github.com/mbta/reduced_fares/pull/276~~
> test: Add a test for the new blind parental consent flow

- data_sources/Production Youth Permissions.csv
This PR adds a new Youth Pass admin user to the Somerville zip codes. 
Asana task: https://app.asana.com/0/1113179098808463/1204653030858440/f
> Chore: Add new Somerville YP admin

- data_sources/Production Youth Permissions.csv
Asana task: https://app.asana.com/0/1113179098808463/1204808392598279/f
This PR makes two changes for the Youth Pass production permissions:
- Removes Austin from access
- Adds `manager@acton-ma.gov` account for access
> Chore: Update YP Admin for Acton

- data_sources/Production Youth Permissions.csv
[Asana task here](https://app.asana.com/0/1113179098808463/1205084063509156/f)
This PR adds one new Admin and removes two outgoing Admin from the Framingham zip codes for the Youth Pass Production data source.
> Chore: Update Framingham YP Prod Admin

- data_sources/Production Youth Permissions.csv
Asana task: https://app.asana.com/0/1113179098808463/1205249383484209/f
This PR adds one new admin and removes one outgoing admin from Malden zip codes for the Youth Pass Production data source.
> Chore: Update Malden YP Admin

- data_sources/Production Youth Permissions.csv
This PR adds a new Youth Pass admin to all Somerville zip codes for the Production data source.
Asana task: https://app.asana.com/0/1113179098808463/1205595727656360/f
> Chore: New Somerville YP admin

- data_sources/Production Youth Permissions.csv
Per [this task](https://app.asana.com/0/1204871882394498/1207494903588997/f). Since we're removing an admin this can be merged regardless of whether or not the user has been removed from Keycloak.
> Remove Chelsea YP Admin

- assets/blind_html/form_elements/blind-access-form-fields.html
- assets/blind_html/form_elements/generated-content.xt
This updates the address copy for the new charlie card store in English and other locales
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207767919269299
> Update Blind workflow copy in RF repo

- .github/workflows/automation-prod.yml
runs all tests for production again
> test: update production tests
