mbta/reduced_fares

- stylesheets/SimpliGov-basic.css
Per the linked Asana ticket below, we need to hide the standard SimpliGov error messages and replace them with custom HTML error elements. This fix updates the SimpliGov stylesheet to hide these standard error messages. 
Asana ticket: https://app.asana.com/0/1170867711449497/1200718287617956/f
> Fix: Update CSS to Hide Error Messages

- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
We've updated the Eligibility Checker to reduce the complexity of progressive disclosure logic. This logic occasionally caused bugs during user testing and QA. 
This PR updates the successful submission Cypress script to match these changes. Test stats following this update:
- 20/20 runs completed 
- 20/20 runs passed
[Asana ticket here](https://app.asana.com/0/1170867711449497/1200989929457797/f) for the Eligibility Checker updates. No corresponding Cypress update ticket.
> Fix: Update Cypress script to match eligibility checker tab changes

- stylesheets/SimpliGov-basic.css
Accessibility testing highlighted that the focus and hover state of our Youth Pass Next/Back/Upload buttons can be improved. This PR adds focus and hover styling to the buttons per [Zeroheight documentation](https://zeroheight.com/2fedee66c/p/95cce7-buttons/b/93e007) to align with MBTA style. 
Asana ticket: https://app.asana.com/0/1170867711449497/1200900718997373/f
> Feat: Add focus and hover to buttons

- data_sources/PreProd Department Permissions Data Source.csv
- data_sources/Training Department Permissions Data Source.csv
In advance of Administrator training on 9/23, we created accounts in training for Administrator testing purposes. This PR creates a data source for the SimpliGov Training environment which maps these training accounts to zip codes. 
Asana ticket: https://app.asana.com/0/1170867711449497/1200984533102007/f
> Feat: Add training data source with test admin accounts

- cypress/automated-tests/youth-pass/address-section-required-fields.spec.js
This PR adds a Cypress script to test required fields within the Home/Mailing Address section of the Youth Pass application. This script ensures that all required fields behave as expected, with error text appearing when a user does not fill out a required field and tries to advance their application. 
Asana ticket: https://app.asana.com/0/1170867711449497/1200759639068403/f
> Feat: Add Address Section Required Fields Cypress Script

- cypress/automated-tests/youth-pass/address-section-required-fields.spec.js
- cypress/automated-tests/youth-pass/personal-contact-sections-required-fields.spec.js
This PR adds an automation script testing the Personal Information and Contact Information sections of the Youth Pass application. 
The script tests that all required fields on both of these sections perform as expected, showing errors when an applicant does not fill out a field and hiding errors when applicants complete the field.
Asana ticket: https://app.asana.com/0/1170867711449497/1200759639068400/f
> Feat: Personal and Contact Info Required Fields Cypress Script

- cypress.json
- package.json
This PR adds scripts to `open` the Cypress automation tool locally and `run` all automation scripts headless. It also updates the Cypress `config` file to no longer record/store videos of test runs, as this is not a desired feature within the Reduced Fares project.
Asana ticket: https://app.asana.com/0/1170867711449497/1201050482135214/f
> Feat: Add Cypress Scripts and Remove Videos

- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
The `successful-submission` Cypress script failed due to some slowness with the Youth Pass Thank You page. This PR updates the script to allow 5 more seconds for this specific assertion. It also breaks the test into smaller `it` blocks for better scoping and more transparent results.
> Fix: Cypress Update Successful Submission Script

- data_sources/PreProd Department Permissions Data Source.csv
- data_sources/Production Department Permissions Data Source.csv
- data_sources/Training Department Permissions Data Source.csv
Add 3 new Boston admins in production, along with 4 more test "Boston" accounts
in pre-prod and 2 in training.
> feat: Add data source slots for 5 more admin users

- .github/workflows/automation-prod.yml
Daylight savings time pushed our automation run back one hour to 11 PM. This PR updates the workflow to run at either 12 AM (during daylight savings) or 1 am, reducing the likelihood of this bumping into an actual application. 
> Fix: Update automation run time

- data_sources/Youth Pass Municipality Contacts and Zip Codes.csv
This PR adds in-person pickup data to the Youth Pass customer service data source. This data will ultimately populate form fields and allow applicants to see relevant details for how to pick up their Youth Pass cards in person. 
Cross-check source for data [available here](https://mbta.sharepoint.com/:x:/s/RevenuePartnerships/EX3pCJJnFhNCgWGgHRAHkbQBm1kUtdxKU_zCiiAdwunXgg?e=0AcjEO).
Asana ticket: https://app.asana.com/0/1170867711449497/1201303342640620/f
> Fix: Add pickup data to customer service data source

- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
This PR updates the Cypress `successful-submission` script to select a card delivery preference (by mail). This work is currently live in the PreProd Youth Pass form, and will be deployed to Prod on 11/18. 
Asana ticket for the front end work: https://app.asana.com/0/1170867711449497/1201303342640612/f
> Fix: Update successful submission script to select card delivery preference

- cypress/automated-tests/youth-pass/address-section-required-fields.spec.js
- cypress/automated-tests/youth-pass/file-type-upload.spec.js
- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
Two Youth Pass automation scripts failed overnight due to changes in Prod. This PR updates these scripts to select a card delivery method. In the `address-section-required-fields` script, a new `it` block tests that a user is not able to progress without selecting a card delivery method. 
> Fix: Update scripts with card delivery options

- .github/workflows/automation-preprod.yml
- .github/workflows/automation-prod.yml
While running the PreProd automation workflow manually, I noticed that it was named incorrectly. This PR updates these workflows to accurately reflect their environments.
> Fix: Update GitHub automation workflow names

- .github/dependabot.yml
Asana ticket: [Set up Dependabot on the reduced_fares repo](https://app.asana.com/0/1170867711449497/1201384476871290)
Check npm dependencies for lockfile-only updates.
I've already turned on Dependabot alerts and security updates in the
GitHub project.
> ci: Configure Dependabot

- data_sources/Production Department Permissions Data Source.csv
Chelsea is getting a new Group Admin for the Youth Pass program. This PR updates the existing data source to grant access to the incoming admin. 
Asana ticket: https://app.asana.com/0/1170867711449497/1201495675913746/f
> Fix: Replace Chelsea group admin user

- cypress/common/birthdate-constants.js
Youth Pass automation scripts began randomly failing on Jan 1, 2022. Some investigation revealed the root cause of these failures is the date math done by automation scripts to calculate applicant ages. 
This PR updates this date math to use a consistent `baselineYear` variable, aligning with the start of the Youth Pass program year (e.g., the 2021-22 program year runs 10/2021 - 09/2022 and will always use 2021 as the `baselineYear`). This aligns our automation scripts with how we treat the Program Year within SimpliGov, as a consistent value based off November 1 of the current program year (e.g., 2021-22 program year uses 11/01/22 within SimpliGov).
No Asana ticket
> Fix: Resolve automation birth year error

- cypress/automated-tests/youth-pass/address-section-required-fields.spec.js
- cypress/automated-tests/youth-pass/eligibility-checker-blockers.spec.js
- cypress/automated-tests/youth-pass/file-type-upload.spec.js
- cypress/automated-tests/youth-pass/personal-contact-sections-required-fields.spec.js
- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
The Reduced Fares team is releasing Language Translations for the Youth Pass application. 
This PR updates Youth Pass automation scripts with necessary changes to accommodate language translations:
- Updated tab numbers for `Next` button element selectors
- Updated IDs for any radio option elements (changes made to strengthen Youth Pass application logic in SimpliGov)
The updated scripts passed 10 local runs within Cypress and a [PreProd GitHub action manual run](https://github.com/mbta/reduced_fares/runs/4704972809?check_suite_focus=true). 
Asana ticket: https://app.asana.com/0/1170867711449497/1201591940415700/f
> Fix: Update automation scripts for Jan release

- transform-environment
While double-checking files today in preparation for a deployment, I noticed a syntax difference between environment names in the input and output files. This PR adds a `"` to the output file, so the environment name matches exactly to the input file. 
> Fix: Transform environment script syntax

- stylesheets/Youth-Pass-Basic.css
The error message on a partially filled email field within the Youth Pass application was not showing as standard ZeroHeight color. This PR updates the CSS file to capture this partially filled field error state. 
Asana ticket: https://app.asana.com/0/1170867711449497/1201613591661873/f
> Fix: Standardize email error color via CSS

- .github/workflows/lint.yml
- package-lock.json
- package.json
- stylesheets/Youth-Pass-Basic.css
Initial step towards: [Set up CSS linting in reduced_fares project](https://app.asana.com/0/1170867711449497/1201752498907673)
Add Prettier as a dependency, refactor existing CSS files in order to get them to pass the check, then run a prettier check in CI on all pushes and PRs.
[Successful CI run](https://github.com/mbta/reduced_fares/runs/5025050541?check_suite_focus=true)
> Set up Prettier for checking and fixing CSS formatting styles

- data_sources/Production Department Permissions Data Source.csv
Brookline's Admin is moving to a new role and should no longer have access to Youth Pass applications or SimpliGov. This PR removes his access via updates to the data source. 
Asana ticket:https://app.asana.com/0/1113545750913664/1201920431671783/f
> Fix: Remove Brookline admin from data source

- data_sources/Production Department Permissions Data Source.csv
Medford let us know that a Youth Pass Admin has left their role. This PR removes the admin from the Youth Pass Prod data source so they will no longer have access to applicant data. 
> Fix: Remove Medford admin from data source

- package-lock.json
[Changelog](https://github.com/prettier/prettier/blob/main/CHANGELOG.md#261)
> chore(deps-dev): bump prettier from 2.5.1 to 2.6.1

- package-lock.json
[Release](https://github.com/cypress-io/cypress/releases/tag/v9.5.2)
> chore(deps-dev): bump cypress from 9.5.1 to 9.5.2

- .github/dependabot.yml
I suspect I copied this from another project where the `package.json` file was located in the `assets` directory.
> fix: Fix npm root directory in dependabot config

- cypress/automated-tests/youth-pass/document-viewer-s3-urls.spec.js
The RF team has noticed flakiness in the S3 URL script. Debugging showed that the SimpliGov dashboard is sometimes not updating following user actions. 
This PR adds `wait` and `click` steps as well as an assertion to basically force-update the SimpliGov dashboard. This is not ideal for automation scripts, but the source code/behavior is out of our control and this behavior is preventing us from testing the intended outcome (Document Viewer URL visibility).
> Fix: S3 URL test dashboard flakiness

- cypress.json
- cypress/automated-tests/youth-pass/document-viewer-s3-urls.spec.js
The S3 URL script needs updates due to recent functionality changes. We enabled a "Cancel request" feature for Group Admin users and this changed the order of the Actions menu. 
I saw continued flakiness in this test when running, so I'm avoiding the Actions menu altogether and using "My records" instead. With changes, the script passed 20 consecutive runs (10 in Cypress UI, 10 in command line) as well as a [passing GitHub Actions run](https://github.com/mbta/reduced_fares/runs/5758184431?check_suite_focus=true).
Note this PR does not yet fix the timed-out PreProd run issue. That is an ongoing issue.
> Fix: S3 URL Script updates

- cypress.json
- cypress/automated-tests/youth-pass/successful-youth-pass-submission.spec.js
We've noticed that some of our Production and PreProd test runs are hanging for 6 hours, then timing out. We observed that this only happens when a script fails and (for some reason) the post-checkout step never kicks off. We theorized that Cypress' default behavior to capture a screenshot might be causing this hang--and we don't use these screenshots for any meaningful purpose.
This PR configures Cypress to no longer capture screenshots of failed tests. Implementing this change on a feature branch caused the a complete test run including several (intentional) failures. 
Asana task: https://app.asana.com/0/1170867711449497/1202049011741428/f
> Fix: Resolve hanging test runs

- .stylelintrc.json
- package-lock.json
- package.json
Asana ticket: [Set up CSS linting in reduced_fares project](https://app.asana.com/0/1200240595613188/1201752498907673)
Use stylelint-config-standard and stylelint-config-prettier for
baseline configuration.
Include this check in the existing `ci:lint` command.
Configuration details:
• Allow vendor prefixes.
• Allow selector id and class patterns to be in any format, don't restrict
to kebab case.
> ci: Install stylelint for css linting

- cypress/automated-tests/senior/birth-date-validation.spec.js
- cypress/automated-tests/senior/required-fields.spec.js
- cypress/automated-tests/senior/successful-senior-submission.spec.js
fix(test): Adjust tests to match new location of instruction screen
I noticed that the Senior tests were failing. Unfortunately they are still failing due to an [actual bug in the form](https://app.asana.com/0/1200856713913621/1202220086281291). ([example failure](https://github.com/mbta/reduced_fares/runs/6278655902?check_suite_focus=true))
> Revert "test: Fix the tests to compensate for hiding the language selection (#89)"

- cypress/automated-tests/youth-pass/admin-application-visibility.spec.js
- cypress/automated-tests/youth-pass/document-viewer-s3-urls.spec.js
Small PR to skip the two tests that require signing into SimpliGov PreProd. This sign-in functionality needs to be reworked following the implementation of SSO for PreProd. 
Asana task for the functionality investigation [is here](https://app.asana.com/0/1170867711449497/1202217735562326/f), and follow-up task to restore these tests [is here](https://app.asana.com/0/1170867711449497/1202220573692328/f).
> Fix: Skip tests requiring SimpliGov sign-in

- .github/workflows/automation-prod.yml
Asana ticket: [Restore running senior tests in prod](https://app.asana.com/0/1201449220161667/1202219930067647)
• Revert "fix: Stop running senior tests in prod for now (#74)"
2a30e1152e89254688bd7fb2cd04c0f4cc44526b
• fix: Specify the production Senior URL
~~Depends on the fix for [Senior: Home address not actually being required](https://app.asana.com/0/1200240595613188/1202220086281291) being deployed to production.~~
> Restore running senior tests in prod

- data_sources/Production Senior Permissions.csv
- data_sources/Training Senior Permissions.csv
We have requests to add new admin for the CharlieCard Store. This PR adds those admin to the data source for both Training and Production environments. 
Asana tasks:
- https://app.asana.com/0/1113179098808463/1202391509377031/f
- https://app.asana.com/0/1113179098808463/1202389178503658/f
> Fix: Add new admin to Training and Prod

- .github/workflows/automation-prod.yml
The Cypress Production run failed overnight following an upgrade to Cypress 10. This PR updates the checkout action in the Production script to allow the tests to run. Sample run [shown here](https://github.com/mbta/reduced_fares/actions/runs/2468827656). 
No Asana task.
> Fix: Restore production scripts

- cypress.config.js
- cypress/automated-tests/senior/required-fields.cy.js
The senior required fields test has been failing in [Prod overnight runs](https://github.com/mbta/reduced_fares/actions/workflows/automation-prod.yml). This PR updates that test to pass consistently. 
No Asana task (there may be one deep in the RF backlog, but I wasn't able to dig it up).
> Fix: Update senior required fields test

- cypress/automated-tests/youth-pass/address-section-required-fields.cy.js
Fixes a periodic source of test failures (e.g. https://github.com/mbta/reduced_fares/runs/7658816700?check_suite_focus=true).
> fix(test): Ensure a field is visible before clicking it

- cypress.config.js
- cypress/automated-tests/youth-pass/address-section-required-fields.cy.js
The Production automation runs have been failing randomly overnight, but they always pass on retry. This is leading to a lot of false negatives and some unnecessary investigation work in the mornings. 
This PR adds a retry value of 2 to the Cypress configuration. Each test will retry failures twice (for a total of 3 attempts). This should help us diagnose actual failures faster and with more confidence. 
No Asana task. I introduced an intentional failure to the repo as roof of concept:
> Feat: Retry Failing Tests

- build/stylesheets/blind.css
- build/stylesheets/senior.css
- build/stylesheets/tap.css
- build/stylesheets/youth.css
- stylesheets/common/_base.scss
Asana tickets:
- [Update CSS to hide calendar](https://app.asana.com/0/1170867711449497/1202841812503975/f)
- [Update rem values on smaller screens](https://app.asana.com/0/1170867711449497/1202799016194917/f)
datetimepicker selector is simplified and is expected to hide the calendar in all cases. The previous CSS provided by SimpliGov did not consistently hide the calendar. SimpliGov does not expect this simplified CSS to cause any issues.
> hide calendar

- data_sources/Production Youth Permissions.csv
This PR removes both Nicole (Newton) and Louis (Malden) from the Youth Pass data source in Production. 
Asana tasks: [Nicole](https://app.asana.com/0/1113179098808463/1203022354547819/f) and [Louis](https://app.asana.com/0/1113179098808463/1203022354547815/f)
> Chore: Remove Newton and Malden YP Admin from Prod

- cypress/automated-tests/blind/required-fields.cy.js
- cypress/automated-tests/blind/successful-blind-submission.cy.js
This PR removes the photo ID field requirement from the blind-required-fields spec. This field is no longer required if a user provides an MCB ID, so the script was failing to find this element and breaking. With this change, we have a successful workflow run in [PreProd](https://github.com/mbta/reduced_fares/actions/runs/3160083166).
[Asana task](https://app.asana.com/0/1170867711449497/1203074321659822/f)
> Fix: Remove no longer required field from script

- cypress/automated-tests/youth-pass/address-section-required-fields.cy.js
- cypress/automated-tests/youth-pass/personal-contact-sections-required-fields.cy.js
- cypress/automated-tests/youth-pass/successful-youth-pass-submission.cy.js
- cypress/common/if-exists.js
This PR adds a selection for the "Which program year..." field so the Youth Pass automation scripts will pass. Note that these changes should be reverted when this field is removed from SimpliGov (on/around October 15). With these changes, we've had a successful run of the [Prod automation scripts](https://github.com/mbta/reduced_fares/actions/runs/3175673238). 
No Asana task for fix. 
Asana task to remove these fields: https://app.asana.com/0/1170867711449497/1203091409919759/f
> Fix: Restore youth pass automation tests

- data_sources/Production Youth Permissions.csv
This PR removes a Quincy Admin from the Youth Pass data source in Production. Asana [task here](https://app.asana.com/0/1113179098808463/1203109101710951/f).
> Chore: Remove Quincy Admin from YP Prod data source

- data_sources/Production Youth Permissions.csv
This PR adds two new Youth Pass admin to Quincy zip codes for the Production data source. 
Asana task: https://app.asana.com/0/1113179098808463/1203142363234723/f
> Chore: Add Quincy Admin to YP Prod data source

- .github/workflows/automation-prod.yml
This PR came from an improvement idea, not an Asana task. If possible, we should try to run the production automation tests automatically every time a change to a `.csv` file is merged to the `main` branch. 
Following [these instructions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs), I believe these changes will accomplish an automatic run of the production tests, removing the necessity to manually run the GitHub workflow every time a data source is changed.
> Feat: Run prod automation scripts automatically on csv merge

- data_sources/Production Youth Permissions.csv
This PR makes three changes to the Youth Pass Production data source:
- Add Maria Belen Power
- Add Ruth Alcantra
- Remove Sam Montano
Asana task: https://app.asana.com/0/1113179098808463/1203648680469040/f
> Chore: Add Maria/Ruth to Chelsea prod admin, remove Sam

- cypress/automated-tests/blind/successful-blind-submission.cy.js
[Update Automated Testing Accordingly](https://app.asana.com/0/696643827122369/1203641337502703/f)
This upload field is no longer on the form.
> fix: Remove the blindness certification upload step

- .stylelintrc.json
- build/stylesheets/blind.css
- build/stylesheets/intake.css
- build/stylesheets/senior.css
- build/stylesheets/tap.css
- build/stylesheets/youth.css
- package-lock.json
- package.json
No ticket. As per https://github.com/mbta/reduced_fares/pull/282, as of Stylelint v15 the `stylelint-config-prettier` package isn't needed any longer.
Extend the standard config.
Remove stylelint-config-prettier as a dependency which is no longer
needed as there should be no conflicting rules.
Update stylelint-config-standard and stylelint-config-standard-scss to
the latest versions.
refactor: Latest css builds
The only changes are with whitespace.
> deps: Upgrade stylelint from 14.3.0 to 15.1.0

- data_sources/Production Youth Permissions.csv
This PR removes three Youth Pass admin from the Production data source:
- Wilfred Wan (Quincy)
- JJ Wang (Quincy)
- Todd Kirrane (Brookline)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204351548129818
> Chore: Remove Quincy and Brookline Admin

- data_sources/Production Youth Permissions.csv
This PR adds a new Youth Pass admin to the Chelsea zip code for the Production data source.
Asana [task here](https://app.asana.com/0/1113179098808463/1204761077431243/f).
> Chore: Add Chelsea Admin to Youth Pass Prod

- data_sources/Production Youth Permissions.csv
This PR removes the `youthpass@acton-ma-gov` email address from all Acton zip codes, per [Reduced Fares team decision](https://app.asana.com/0/0/1204808392598279/1204862680228953/f).
> Fix: Remove Group Email from Acton Youth Pass

- data_sources/Production Youth Permissions.csv
This PR updates the Youth Pass production data source with a new Admin from Acton. 
Please note: The Admin proactively created an account in Keycloak using `actonma.gov` (with no dash). Our naming convention has historically included a dash for Acton, but I had to omit it for this PR so the data source would match with the user login email. If this should be handled differently, I'm open to whatever solution suits the Fares Tech team.
> Chore: Add New Acton YP Admin

- assets/intake_html/form_elements/generated-content.txt
Updates CSC address copy for Intake form content in SimpliGov in all languages.
This form has references to the CharlieCard Store, but no references to the address. Changing these has been designated out of scope for this update.
The only remaining references for this are in the "Generated Content" fields that drive emails and PDFs. I've added a file to track the content of those here.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207767916523316
> Intake form copy updates for CSC move
